// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKAgGzRMieJZyQoeNAOka6O3DTXtoTew4',
    appId: '1:1082113918718:web:67d3b1aa2a91ce51e7c7af',
    messagingSenderId: '1082113918718',
    projectId: 'financial-goal-tracker-dbd70',
    authDomain: 'financial-goal-tracker-dbd70.firebaseapp.com',
    storageBucket: 'financial-goal-tracker-dbd70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiMESWjOjPTPK7tGatrC8tEDkElunljc',
    appId: '1:1082113918718:android:97ecca9ae9c77fdde7c7af',
    messagingSenderId: '1082113918718',
    projectId: 'financial-goal-tracker-dbd70',
    storageBucket: 'financial-goal-tracker-dbd70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0KXD_v91-BoOF3Bn85djroP2CAb7ASI',
    appId: '1:1082113918718:ios:a6b8d7be5c913941e7c7af',
    messagingSenderId: '1082113918718',
    projectId: 'financial-goal-tracker-dbd70',
    storageBucket: 'financial-goal-tracker-dbd70.appspot.com',
    iosBundleId: 'com.example.financialGoalDetail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ0KXD_v91-BoOF3Bn85djroP2CAb7ASI',
    appId: '1:1082113918718:ios:76dfe545def3bea3e7c7af',
    messagingSenderId: '1082113918718',
    projectId: 'financial-goal-tracker-dbd70',
    storageBucket: 'financial-goal-tracker-dbd70.appspot.com',
    iosBundleId: 'com.example.financialGoalDetail.RunnerTests',
  );
}
